# Script to deploy on the render cloud platform

name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env: 
        webhook_url: "https://api.render.com/deploy/srv-cioe9jtgkuvh5gnd2tn0?key=nLq92Ir9-_g"
        webhook_secrets: "nLq92Ir9-_g"

    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY1}} #this is the github token
        service-id: "srv-cioe9jtgkuvh5gnd2tn0" #this id is unique for each app
        retries: 20
        wait: 16000
        sleep: 30000



        